name: llm_chat_flutter
description: "A Flutter chat application that interfaces with LLM models, inspired by LLMFarm"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  markdown_widget: ^2.3.2+6
  flutter_markdown: ^0.7.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/downloadable_models.json 